apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-configmap
data:
  ALLOWED_HOSTS: '*'
  DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@192.168.0.107:5432/test_k8s
  DEBUG: 'False'
  SECRET_KEY: your-secret-key