apiVersion: v1

kind: Pod
metadata:
  name: django-app
  labels:
    app.kubernetes.io/name: django-app
spec:
  containers:
    - name: django-app-container
      image: django_app
      imagePullPolicy: Never
      env:
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          value: "sdfudfhhu3hfu39443f"
        - name: DATABASE_URL
          value: "postgres://test_k8s:OwOtBep9Frut@10.0.2.2:6666/test_k8s"
        - name: ALLOWED_HOSTS
          value: "*"